on:
  push:
    branches:
      - master
jobs:
  run_pull:
    name: run pulls
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Use node lts
        uses: actions/setup-node@v4
        with:
            node-version: lts/*
      - name: Checks new files
        run: |
            node -v
            echo "Running npm i"
            npm i
            echo "Running run build"
            npm run build

    #   - name: install ssh keys
    #     uses: appleboy/ssh-action@v0.1.10
    #     with:
    #       host: ${{secrets.HOST}}
    #       username: ${{secrets.USERNAME}}
    #       key: ${{ secrets.SSH_PRIVATE_KEY}}
    #       port: ${{ secrets.PORT }}
    #       command_timeout: 30m
    #       script: |
    #         cd ~/strapi-test
    #         git pull origin master
    #         echo "That worked hopefully"
