name: Test and pull
on:
  push:
    branches:
      - master
jobs:
  code_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Use node lts
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Checks node and runs build
        run: |
          ls -la
          node -v
          echo "Running npm i"
          npm i
          echo "Running run build"
          npm run build
  deploy:
    needs: code_test
    runs-on: ubuntu-latest
    steps:
      - name: SSH Connection and pull
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: |
            cd ~/${{github.event.repository.name}}
            git pull origin master
            echo "That worked hopefully"
      - name: Runs npm i
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: |
            cd ~/${{github.event.repository.name}}
            npm i
            npm run build
      - name: Runs npm build
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{secrets.HOST}}
            username: ${{secrets.USERNAME}}
            key: ${{ secrets.SSH_PRIVATE_KEY}}
            port: ${{ secrets.PORT }}
            command_timeout: 30m
            script: |
                cd ~/${{github.event.repository.name}}
                npm run build
  error:
    runs-on: ubuntu-latest
    needs: code_test
    if: failure()
    steps:
        - name: Failed message
          run: echo "It seems something failed, check the project code"