on:
  push:
    branches:
      - master
jobs:
  run_pull:
    name: run pulls
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Checks new files
        run: npm run build
